"""Durable Studio project files and deterministic Python export."""

from __future__ import annotations

import json
from pathlib import Path
from pprint import pformat
from uuid import uuid4

from .models import StudioDocument, StudioNode


class ProjectFile:
    """A JSON Studio document persisted with atomic file replacement."""

    def __init__(self, path: str | Path) -> None:
        self.path = Path(path)

    def load(self) -> StudioDocument:
        """Load and validate the project document."""
        return StudioDocument.model_validate_json(self.path.read_text(encoding="utf-8"))

    def save(self, document: StudioDocument) -> None:
        """Atomically replace the project with ``document``."""
        value = json.dumps(document.model_dump(mode="json"), allow_nan=False, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
        _atomic_write(self.path, value)


def export_python(document: StudioDocument) -> str:
    """Render ``document`` as deterministic, ordinary spaday Python authoring code."""
    nodes: list[StudioNode] = []
    children: list[list[tuple[str, int]]] = []

    def collect(node: StudioNode) -> int:
        index = len(nodes)
        nodes.append(node)
        children.append([])
        for slot in sorted(node.slots):
            for child in node.slots[slot]:
                children[index].append((slot, collect(child)))
        return index

    collect(document.root)
    lines = [
        "# Generated by spaday-studio. Edit the Studio project, then export again.",
        "from spaday import Component, element",
        "",
        "",
        "def page() -> Component:",
    ]
    for index, node in enumerate(nodes):
        lines.append(f"    node_{index} = element({_literal(node.tag)}, key={_literal(node.key or node.id)})")
        for name in sorted(node.props):
            _append_prop(lines, index, name, node.props[name])
        _append_prop(lines, index, "data-spaday-studio-id", node.id)
    for index, child_nodes in enumerate(children):
        for slot, child_index in child_nodes:
            if slot == "default":
                lines.append(f"    node_{index}.child(node_{child_index})")
            else:
                lines.append(f"    node_{index}.child_in({_literal(slot)}, node_{child_index})")
    lines.extend(("    return node_0", "", "", '__all__ = ["page"]', ""))
    return "\n".join(lines)


def _literal(value: object) -> str:
    return pformat(_normalized(value), width=100, sort_dicts=True)


def _append_prop(lines: list[str], index: int, name: str, value: object) -> None:
    name_literal = _literal(name)
    value_literal = _literal(value)
    statement = f"    node_{index}.prop({name_literal}, {value_literal})"
    if "\n" not in statement and len(statement) <= 120:
        lines.append(statement)
        return
    lines.extend((f"    node_{index}.prop(", f"        {name_literal},"))
    lines.extend(f"        {line}" for line in value_literal.splitlines())
    lines.append("    )")


def _normalized(value: object) -> object:
    if isinstance(value, dict):
        return {key: _normalized(value[key]) for key in sorted(value)}
    if isinstance(value, list):
        return [_normalized(item) for item in value]
    return value


def _atomic_write(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{uuid4().hex}.tmp")
    try:
        temporary.write_text(value, encoding="utf-8")
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


__all__ = ["ProjectFile", "export_python"]
